/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsapp;

import javax.swing.JOptionPane;

/**
 *
 * @author jefloresca
 */
public class SendSms extends javax.swing.JFrame {

    /**
     * Creates new form SendSms
     */
    private String senderNumber;
    private String message;
    
    public SendSms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendSmsLabel = new javax.swing.JLabel();
        senderLabel = new javax.swing.JLabel();
        senderField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        btnSendsms = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        sendSmsLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        sendSmsLabel.setText("Send SMS");

        senderLabel.setText("Sender's #");

        messageLabel.setText("Message: ");

        messageArea.setColumns(20);
        messageArea.setRows(5);
        jScrollPane1.setViewportView(messageArea);

        btnSendsms.setText("Send");
        btnSendsms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendsmsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sendSmsLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(senderLabel)
                            .addGap(18, 18, 18)
                            .addComponent(senderField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(messageLabel)
                        .addComponent(jScrollPane1))
                    .addComponent(btnSendsms))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendSmsLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senderLabel)
                    .addComponent(senderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSendsms)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendsmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendsmsActionPerformed
        // TODO add your handling code here:
        senderNumber = senderField.getText();
        message = messageArea.getText();
        final Msg msg = new Msg();
        try
        {
            if(senderNumber.isEmpty() && message.isEmpty())
            { 
                JOptionPane.showMessageDialog(rootPane, "Please fill up all fields.");
            }
            else
            {
                if(!senderNumber.equals(""))
                {
                    if(msg.validate(senderNumber))
                    {
                        // Send SMS
                        msg.sendSMS(senderNumber, message);
                        // Insert Log
                        Database db = new Database();
                        db.insertLogs(senderNumber, message);
                        messageArea.setText("");
                        senderField.setText("");
                    } 
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Invalid Number!");

                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Phone Number cannot be empty");
                }
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
            
        }
    }//GEN-LAST:event_btnSendsmsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendSms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendSms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendSms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendSms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendsms;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel sendSmsLabel;
    private javax.swing.JTextField senderField;
    private javax.swing.JLabel senderLabel;
    // End of variables declaration//GEN-END:variables
}
